Add price filter
cuappdev/resell-backend pull request #59
Opened 2023-03-08 23:25 UTC by akmatchev

## Overview

## Changes Made

## Test Coverage

2023-03-08 23:46 UTC, mateow99 approved these changes
Just address that issue of people seeing own posts across all the post routes. maybe should be its own pr so I'm approving for now.

2023-03-08 23:46 UTC, mateow99 commented on src/repositories/PostRepository.ts
> +      .andWhere("post.archive = false")
should also have `.andWhere("post.user != user.id)` to eliminate people seeing their own posts.

2023-03-09 23:45 UTC, snajima requested changes
great first pr! address the problems i addressed above first :)

2023-03-09 23:45 UTC, snajima commented on src/repositories/PostRepository.ts
> +import internal from 'stream';
what is this for?

2023-03-09 23:45 UTC, snajima commented on src/tests/PostTest.test.ts
> +import { Controller } from 'routing-controllers';
and this?

2023-03-09 23:45 UTC, snajima commented on src/tests/PostTest.test.ts
> +    getPostsResponse = await postController.filterPostsByPrice(filter);
how are these test cases different from each other? if they're not, label this test case as something a little more informative (e.g. `filter posts by price, where price is within range`). if they are, separate them into different test cases.

2023-03-14 19:09 UTC, snajima approved these changes
lgtm, let's get this merged! also, make sure u hit "re-request review" so i get notified when u address my comments :)

2023-03-14 22:32 UTC, merged